### ISSUE TITLE
minimum GPU memory

### ISSUE THREAD

**Issue by ZhaoqunZhong** [XiaoyuShi97/VideoFlow#10]
Hi, 
I'm using an RTX2080 with 8G memory, I got "CUDA out of memory" error even if I reduced the number of images to 5 in MOF mode. I wonder what's the minimum GPU memory necessary to get inference to work. 
Thanks~

**Comment by XiaoyuShi97** [comment]
Hi, thanks for your interest in our work. I did not test this requirement before. May I ask what is the resolution of your input images?

**Comment by ZhaoqunZhong** [comment]
sorry, forgot to provide that, it's 1280x720.

**Comment by XiaoyuShi97** [comment]
Ok. Did you try mix-precision inference? And I will update (in this week) support for https://github.com/princeton-vl/RAFT#optional-efficent-implementation, which save GPU memory at the expense of more running time.

**Comment by ZhaoqunZhong** [comment]
Just tried setting _CN.mixed_precision = True in the kitti_multiframes.py file, if that's what you meant by mix-precision inference. The result is the same. I'm using the kitti_multiframes and kitti for MOF and BOF mode respectively, because my data is urban road image, which the kitti config is more suitable for, I think? Could that cause more gpu memory consumption? Plus, I'm using cuda version 11+, not cuda 10.x.

**Comment by XiaoyuShi97** [comment]
Hi, if you are using inference.py for inference, you should modify https://github.com/XiaoyuShi97/VideoFlow/blob/main/configs/multiframes_sintel_submission.py . Decreasing decoder_depth should bring clear memory reduction. Yes, kitti.ckpt should be good and cuda version does not matter from my experience.

**Comment by ZhaoqunZhong** [comment]
Hi, this is my modified configs/kitti_multiframes.py, I'm using this instead of multiframes_sintel_submission.py. 
```
from yacs.config import CfgNode as CN
_CN = CN()

_CN.name = ''
_CN.suffix =''
_CN.gamma = 0.85
_CN.max_flow = 400
_CN.batch_size = 8
_CN.sum_freq = 100
_CN.val_freq = 100000000
_CN.image_size = [1080, 720]
_CN.add_noise = False
_CN.use_smoothl1 = False
_CN.critical_params = []

_CN.network = 'MOFNetStack'

_CN.model = 'VideoFlow_ckpt/MOF_kitti.pth'
_CN.input_frames = 5
_CN.restore_ckpt = None
_CN.mixed_precision = True

###################################################
###################################################
_CN.MOFNetStack = CN()
_CN.MOFNetStack.pretrain = True
_CN.MOFNetStack.Tfusion = 'stack'
_CN.MOFNetStack.cnet = 'twins'
_CN.MOFNetStack.fnet = 'twins'
_CN.MOFNetStack.down_ratio = 8
_CN.MOFNetStack.feat_dim = 256
_CN.MOFNetStack.corr_fn = 'default'
_CN.MOFNetStack.corr_levels = 4
_CN.MOFNetStack.mixed_precision = False
_CN.MOFNetStack.context_3D = False
_CN.MOFNetStack.GMA_MF = False

_CN.MOFNetStack.decoder_depth = 12
_CN.MOFNetStack.critical_params = ["cnet", "fnet", "pretrain", 'corr_fn', "Tfusion", "corr_levels", "decoder_depth", "mixed_precision", "GMA_MF"]

### TRAINER
_CN.trainer = CN()
_CN.trainer.scheduler = 'OneCycleLR'
_CN.trainer.optimizer = 'adamw'
_CN.trainer.canonical_lr = 12.5e-5
_CN.trainer.adamw_decay = 1e-4
_CN.trainer.clip = 1.0
_CN.trainer.num_steps = 25000
_CN.trainer.epsilon = 1e-8
_CN.trainer.anneal_strategy = 'linear'
def get_cfg():
    return _CN.clone()
```
The decoder depth is already 12, should I further reduce it? Thanks for your detail help, I don't have a lot of DL experience.

**Comment by MichalTurek** [comment]
Would  such change decrease output flow quality?

**Comment by XiaoyuShi97** [comment]
Generally depth=12 is enough and larger depth brings very little improvements.

**Comment by MichalTurek** [comment]
For my case  changing the depth, does not change  required memory (same issue for  12 and 32) :

```
VideoFlow_ckpt/MOF_sintel.pth
Parameter Count: 13453240
preparing image...
Input image sequence dir = C:\Users\micha\Downloads\VideoFlow-main\VideoFlow-main\demo_input_images
Traceback (most recent call last):
  File "C:\Users\micha\Downloads\VideoFlow-main\VideoFlow-main\inference.py", line 114, in <module>
    flow_pre = MOF_inference(model.module, cfg)
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\micha\Downloads\VideoFlow-main\VideoFlow-main\inference.py", line 64, in MOF_inference
    flow_pre, _ = model(input_images, {})
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\micha\Downloads\VideoFlow-main\VideoFlow-main\core\Networks\MOFNetStack\network.py", line 150, in forward
    fmaps = self.fnet(images.reshape(B*N, 3, H, W)).reshape(B, N, -1, H//down_ratio, W//down_ratio)
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\micha\Downloads\VideoFlow-main\VideoFlow-main\core\Networks\encoders.py", line 29, in forward
    x = blk(x, size)
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\micha\anaconda3\lib\site-packages\timm\models\twins.py", line 215, in forward
    x = x + self.drop_path(self.attn(self.norm1(x), size))
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\micha\anaconda3\lib\site-packages\timm\models\twins.py", line 186, in forward
    attn = (q @ k.transpose(-2, -1)) * self.scale
RuntimeError: CUDA out of memory. Tried to allocate 15.30 GiB (GPU 0; 8.00 GiB total capacity; 1.68 GiB already allocated; 3.93 GiB free; 1.84 GiB reserved in total by PyTorch)
```
I am trying to generate flow for 1080p images

**Comment by XiaoyuShi97** [comment]
It seems using depth=12 already exceeds the GPU memory. I will update the efficient implementation and you can have a try.

**Comment by XiaoyuShi97** [comment]
Hi @ZhaoqunZhong @MichalTurek , I have updated the efficient cost volume implementation, which should save some GPU memory. Please refer to README and let me know if there are any other problems.

**Comment by MichalTurek** [comment]
One last question, is it worst quality-wise flow with this implementation?

**Comment by XiaoyuShi97** [comment]
No. It should yield the same results. Let me know if you have other questions.

**Comment by MichalTurek** [comment]
I get fallowing error while trying to install using readme:
`C:\Users\micha\anaconda3\lib\site-packages\torch\include\c10/util/Optional.h(361): note: see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
        with
        [
            T=std::vector<std::vector<torch::autograd::profiler::LegacyEvent,std::allocator<torch::autograd::profiler::LegacyEvent>>,std::allocator<std::vector<torch::autograd::profiler::LegacyEvent,std::allocator<torch::autograd::profiler::LegacyEvent>>>>
        ]
C:\Users\micha\anaconda3\lib\site-packages\torch\include\c10/util/Optional.h(418): note: see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
        with
        [
            T=std::vector<std::vector<torch::autograd::profiler::LegacyEvent,std::allocator<torch::autograd::profiler::LegacyEvent>>,std::allocator<std::vector<torch::autograd::profiler::LegacyEvent,std::allocator<torch::autograd::profiler::LegacyEvent>>>>
        ]
C:\Users\micha\anaconda3\lib\site-packages\torch\include\c10/util/Optional.h(418): note: see reference to alias template instantiation 'c10::OptionalBase<std::vector<std::vector<torch::autograd::profiler::LegacyEvent,std::allocator<torch::autograd::profiler::LegacyEvent>>,std::allocator<std::vector<torch::autograd::profiler::LegacyEvent,std::allocator<torch::autograd::profiler::LegacyEvent>>>>>' being compiled
C:\Users\micha\anaconda3\lib\site-packages\torch\include\torch/csrc/autograd/profiler_legacy.h(562): note: see reference to class template instantiation 'c10::optional<std::vector<std::vector<torch::autograd::profiler::LegacyEvent,std::allocator<torch::autograd::profiler::LegacyEvent>>,std::allocator<std::vector<torch::autograd::profiler::LegacyEvent,std::allocator<torch::autograd::profiler::LegacyEvent>>>>>' being compiled
C:\Users\micha\anaconda3\lib\site-packages\torch\include\c10/util/Optional.h(387): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
        with
        [
            T=std::vector<std::vector<torch::autograd::profiler::LegacyEvent,std::allocator<torch::autograd::profiler::LegacyEvent>>,std::allocator<std::vector<torch::autograd::profiler::LegacyEvent,std::allocator<torch::autograd::profiler::LegacyEvent>>>>
        ]
C:\Users\micha\anaconda3\lib\site-packages\torch\include\c10/util/Optional.h(181): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
        with
        [
            T=std::vector<at::Tensor,std::allocator<at::Tensor>>
        ]
C:\Users\micha\anaconda3\lib\site-packages\torch\include\c10/util/Optional.h(361): note: see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
        with
        [
            T=std::vector<at::Tensor,std::allocator<at::Tensor>>
        ]
C:\Users\micha\anaconda3\lib\site-packages\torch\include\c10/util/Optional.h(418): note: see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
        with
        [
            T=std::vector<at::Tensor,std::allocator<at::Tensor>>
        ]
C:\Users\micha\anaconda3\lib\site-packages\torch\include\c10/util/Optional.h(418): note: see reference to alias template instantiation 'c10::OptionalBase<std::vector<at::Tensor,std::allocator<at::Tensor>>>' being compiled
C:\Users\micha\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include\torch/optim/lbfgs.h(44): note: see reference to class template instantiation 'c10::optional<std::vector<at::Tensor,std::allocator<at::Tensor>>>' being compiled
C:\Users\micha\anaconda3\lib\site-packages\torch\include\c10/util/Optional.h(387): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
        with
        [
            T=std::vector<at::Tensor,std::allocator<at::Tensor>>
        ]
correlation.cpp(28): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
correlation.cpp(29): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
correlation.cpp(30): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
correlation.cpp(42): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
correlation.cpp(43): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
correlation.cpp(44): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
correlation.cpp(45): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc" -c correlation_kernel.cu -o build\temp.win-amd64-cpython-39\Release\correlation_kernel.obj -IC:\Users\micha\anaconda3\lib\site-packages\torch\include -IC:\Users\micha\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\micha\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\micha\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IC:\Users\micha\anaconda3\include -IC:\Users\micha\anaconda3\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=alt_cuda_corr -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --use-local-env
correlation_kernel.cu
C:/Users/micha/anaconda3/lib/site-packages/torch/include\c10/macros/Macros.h(189): warning C4067: unexpected tokens following preprocessor directive - expected a newline
nvcc error   : 'cudafe++' died with status 0xC00000FD (STACK_OVERFLOW)
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\bin\\nvcc.exe' failed with exit code 253`

**Comment by XiaoyuShi97** [comment]
I did not encounter such error. It seems to be related with Windows. Could check https://forums.developer.nvidia.com/t/ptxas-died-with-status-0xc00000fd-stack-overflow/57143/3 or google with the error message.

**Comment by MichalTurek** [comment]
I've managed to run setup.py, generated correlation files: 
<img width="177" alt="image" src="https://github.com/XiaoyuShi97/VideoFlow/assets/87382140/3f01490f-2870-4670-a728-c8b1190dbe89">

However after changing the flag in multiframes_sintel_submission.py : 
<img width="348" alt="image" src="https://github.com/XiaoyuShi97/VideoFlow/assets/87382140/c5ab7082-a95b-4001-836a-0f80e8383947">
I still get the same error 
`preparing image...
Input image sequence dir = C:\Users\micha\Downloads\VideoFlow-main\VideoFlow-main\demo_input_images
Traceback (most recent call last):
  File "C:\Users\micha\OneDrive\Pulpit\videoflow\VideoFlow\inference.py", line 114, in <module>
    flow_pre = MOF_inference(model.module, cfg)
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\micha\OneDrive\Pulpit\videoflow\VideoFlow\inference.py", line 64, in MOF_inference
    flow_pre, _ = model(input_images, {})
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\micha\OneDrive\Pulpit\videoflow\VideoFlow\core\Networks\MOFNetStack\network.py", line 150, in forward
    fmaps = self.fnet(images.reshape(B*N, 3, H, W)).reshape(B, N, -1, H//down_ratio, W//down_ratio)
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\micha\OneDrive\Pulpit\videoflow\VideoFlow\core\Networks\encoders.py", line 29, in forward
    x = blk(x, size)
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\micha\anaconda3\lib\site-packages\timm\models\twins.py", line 215, in forward
    x = x + self.drop_path(self.attn(self.norm1(x), size))
  File "C:\Users\micha\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\micha\anaconda3\lib\site-packages\timm\models\twins.py", line 187, in forward
    attn = attn.softmax(dim=-1)
RuntimeError: CUDA out of memory. Tried to allocate 11.47 GiB (GPU 0; 8.00 GiB total capacity; 6.31 GiB already allocated; 0 bytes free; 6.37 GiB reserved in total by PyTorch)
`
command I use: 
` python -u inference.py --mode MOF --seq_dir C:\Users\micha\Downloads\VideoFlow-main\VideoFlow-main\demo_input_images --vis_dir C:\Users\micha\Downloads\VideoFlow-main\VideoFlow-main\demo_input_images`
I belive that this correlation method is not the issue, as I get error in line 150, before corr_fn is even used: 
<img width="816" alt="image" src="https://github.com/XiaoyuShi97/VideoFlow/assets/87382140/9d5fefb6-5aee-4cf7-8cc5-b4f8d9afffa8">

**Comment by XiaoyuShi97** [comment]
Hi, still out of memory. Maybe try down-sample the images and up-sample the predicted flows.

**Comment by jiangxiaogg** [comment]
谢谢你们的工作。我来总结下这个减小显存占用的方法（中文）1.确保安装的setuptools版本不要高于70.0.0，亲测69.5.1版本可以进行编译CUDA扩展。2.进入alt_cuda_corr文件夹，运行setup.py文件，在终端就使用python setup.py install进行运行，随后退出alt_cuda_corr文件夹路径到工程根路径，运行推理即可。这样就是单纯的推理，没有反向传播。
之前15张1280*720的图片，超过12G显存，用了这个方法，可以一次性进行24张这样图片的推理
